# Copyright (c) 2015-2016, NVIDIA CORPORATION.  All rights reserved.

sudo: required
dist: trusty

language: python
python: 2.7

env:
    matrix:
        - LINT_CHECK=true
        - DIGITS_TEST_FRAMEWORK=caffe CAFFE_FORK=NVIDIA
        - DIGITS_TEST_FRAMEWORK=caffe CAFFE_FORK=BVLC
        - DIGITS_TEST_FRAMEWORK=torch
        - DIGITS_TEST_FRAMEWORK=none
        - DEB_BUILD=true

cache:
    apt: true
    directories:
        - ~/caffe
        - ~/torch

services:
    - docker

before_install:
      # envvar calculations
    - export LINT_CHECK=${LINT_CHECK:-false}
    - export DEB_BUILD=${DEB_BUILD:-false}
    - if $DEB_BUILD || $LINT_CHECK; then export RUN_TESTS=false; else export RUN_TESTS=true; fi
    - if $RUN_TESTS && [ "$DIGITS_TEST_FRAMEWORK" == "torch" ]; then export TEST_TORCH=true; else export TEST_TORCH=false; fi

      # create new virtualenv
    - deactivate
    - virtualenv --system-site-packages ~/venv
    - source ~/venv/bin/activate

install:
    - ./scripts/travis/install-apt.sh
    - if $RUN_TESTS; then ./scripts/travis/install-caffe.sh ~/caffe; fi
    - if $TEST_TORCH; then travis_wait ./scripts/travis/install-torch.sh ~/torch; fi
    - if $RUN_TESTS; then ./scripts/travis/install-python-requirements.sh; fi
    - if $RUN_TESTS; then ./scripts/travis/install-digits.sh; fi

script:
    - if $RUN_TESTS; then ./scripts/travis/run-tests.sh; fi
    - if $LINT_CHECK; then ./digits-lint; fi
    - if $DEB_BUILD; then ./scripts/travis/deb-build.sh; fi

